### PR TITLE
Set the content type as application/json

### PR DESCRIPTION
**Pull request by andyzg**
I copied off the jsonify function like you told me to check out from 
https://github.com/UWFlow/rmc/blob/master/server/api/api_util.py#L91
I removed the ApiJsonEncoder, wasn't sure if it was needed here. Let me know if I should add it back.

### CODE REVIEW

**Comment by jonafato** [comment]
Has this pull request been abandoned? Issue #4 should be a quick fix, and I'm happy to submit a new one if this is no longer being worked on.

**Comment by divad12** [comment]
It should indeed have been a quick fix! Sorry @andyzg for asking you to do a whole bunch of non-issue related refactoring — that should've been a request for another PR.

Thanks for the bump @jonafato. I did not notice code review comments were addressed on August 21 (or maybe I did and put it off till I forgot).

Will look into merging.

**Comment by divad12** [comment]
Resolved conflict and manually merged! (Created a branch from this PR, merge into master, resolve conflicts, commit merge.)

You still get credit for these commits @andyzg: https://github.com/divad12/vim-awesome/commits/master?author=andyzg

Thanks for addressing all those comments, and sorry about the delay in getting back!

**Comment by divad12** [comment]
Closes #4

**Pull request merged**
