### PR TITLE
Remove "unmaintained" note in Readme

### PR DESCRIPTION
**Pull request by captbaritone**
Now that I've been given commit permissions, and we have some forward momentum,
I think it's okay to remove message.

### CODE REVIEW

**Comment by spicyj** [comment]
Yay, do it! Thank you.

**Comment by divad12** [comment]
w00tt!!! awesome!

I'm wondering if there are other honours or things we can do to make the maintainer transition more formal, or announce it in some way?

I'm happy to move this repo to an org. Anything else that'd be appropriate to do to signal?

**Comment by captbaritone** [comment]
I think we should probably plan some sort of announcement, but let's wait until we actually get the dupes removed, and our scraping caught up a bit.

Moving to an organization would be a nice gesture for sure. Maybe we could plan that move to coincide with the publicity push? Might make a nice bit of ceremony.


--
Jordan Eldredge

Please excuse any typos or terseness; this email was sent from a mobile device.

**Comment by divad12** [comment]
Sounds good to me, thanks for the work so far!

**Pull request merged**
